# Generated by Django 4.1.7 on 2023-06-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="alumni", name="others",),
        migrations.AlterField(
            model_name="alumni",
            name="othernames",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
