# Generated by Django 4.2 on 2024-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('field_officer', 'Field Officer'), ('officer', 'Officer')], default='officer', max_length=20),
        ),
    ]
