# Generated by Django 4.2 on 2024-12-10 17:53

from django.db import migrations, models
import django.db.models.deletion

def create_initial_data(apps, schema_editor):
    District = apps.get_model('graduates', 'District')
    Course = apps.get_model('graduates', 'Course')
    ExamCenter = apps.get_model('graduates', 'ExamCenter')
    Graduate = apps.get_model('graduates', 'Graduate')
    
    # Create a default district
    default_district = District.objects.create(
        name='Default District',
        region='Default Region'
    )
    
    # Create a default exam center
    default_center = ExamCenter.objects.create(
        code='DEFAULT',
        name='Default Center',
        district=default_district
    )
    
    # Create courses from existing graduate course names
    existing_courses = Graduate.objects.values_list('course_name', flat=True).distinct()
    courses = {}
    for course_name in existing_courses:
        if course_name:
            course = Course.objects.create(
                code=f'C{len(courses) + 1:03d}',
                name=course_name,
                department='Default Department'
            )
            courses[course_name] = course
    
    # Update existing graduates
    for graduate in Graduate.objects.all():
        if graduate.course_name in courses:
            graduate.course_temp = courses[graduate.course_name]
        else:
            # Create a course if it doesn't exist
            course = Course.objects.create(
                code=f'C{len(courses) + 1:03d}',
                name=graduate.course_name or 'Unknown Course',
                department='Default Department'
            )
            graduate.course_temp = course
        
        graduate.district = default_district
        graduate.exam_center = default_center
        graduate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduates.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='graduate',
            old_name='employment_date',
            new_name='employment_start_date',
        ),
        migrations.AddField(
            model_name='graduate',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.district'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='exam_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.examcenter'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='course_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.course'),
        ),
        migrations.RunPython(create_initial_data),
        migrations.RemoveField(
            model_name='graduate',
            name='course_name',
        ),
        migrations.RenameField(
            model_name='graduate',
            old_name='course_temp',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduates.course'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduates.district'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='exam_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduates.examcenter'),
        ),
    ]
